### PR TITLE
RA-965 Built module for OpenMRS 2.0 platform

### PR DESCRIPTION
**Pull request by jdegraft**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@jdegraft i thought admin links are simply handled by having the legacyui module dependency in the pom. Atleast that is what i have been doing for all modules having admin links and all works well.

**Comment by jdegraft** [comment]
@dkayiwa is it not necessary to add legacyui in pom for 2.0 module as legacyui is not available in platform 1.10? Bear with me, I am still trying to understand how to make changes for these builds.

**Comment by dkayiwa** [comment]
@jdegraft the actual classes in the legacyui module are already existing in platforms before 2.0
In other words, before 2.0, they are in the core platform, while from 2.0 and above, they are in a module.

**Comment by jdegraft** [comment]
@dkayiwa I see what you mean, so I just have to add it. I will correct the pull request.

**Comment by jdegraft** [comment]
@dkayiwa should I go ahead and add the legacyui in the pom, it seems an earlier commit doing that was reverted?

**Comment by dkayiwa** [comment]
@jdegraft just do only that which is required to have the module compile and run well. :)

**Pull request closed without merging**
