### PR TITLE
ATLAS-53: Should not show atlas link on admin page if user doesn't have necessary privilege

### PR DESCRIPTION
**Pull request by HelioStrike**
Link to JIRA issue: https://issues.openmrs.org/browse/ATLAS-53

While the main part of the issue is done, I'm stuck at writing unit tests for it. If there is no authenticated user, we receive no links, but I've no idea how to simulate an authenticated user with the necessary privilege. If someone could give me the necessary pointers, I'd be really grateful. Thank you.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you take a look at the travis failure?

**Comment by HelioStrike** [comment]
@dkayiwa "contextDAO is null". I looked it up online but couldn't find any solution.

**Comment by HelioStrike** [comment]
@dkayiwa I tried ignoring the test would be affected by my code changes and it looks like the "contextDAO is null" problem is present even before the changes. What would suggest I do to solve it?

**Comment by mozzy11** [comment]
@HelioStrike , does the atlas module build successfully on your local machine ?? copmletely before you touch it??

**Comment by HelioStrike** [comment]
@mozzy11 Yup, it builds successfully on my local machine even after the changes.

**Comment by mozzy11** [comment]
i think if youre able to make it buil succesfully on your local machine before touching it, you can be able to track which of your local changes leads to the above error

**Comment by HelioStrike** [comment]
I think 'Context.openSession()' is the cause of the failure, but I'll be needing it for my tests to do what I want them to. I'll see what I can do...

**Comment by HelioStrike** [comment]
I've been busy with stuff, so I'll close this PR for now.

**Pull request closed without merging**
