### PR TITLE
RA-965 Built module for OpenMRS platform 2.0

### PR DESCRIPTION
**Pull request by jdegraft**

### CODE REVIEW

**Comment by djazayeri** [comment]
I still do not understand the approach we are taking here. From peeking at this code it seems to me that we are making the Atlas module require openmrs-core version 2.0. But that is not acceptable, because we don't want to lose compatibility with still-supported 1.x release branches.

**Comment by wluyima** [comment]
I agree with Darius, these tickets are just about verifying that these modules can run on platform 2.0 and making any changes where necessary while preserving backwards compatibility with older platform versions

**Comment by jdegraft** [comment]
My limited understanding of java (and OpenMRS) may be the culprit here.
My approach to confirm the modules run on platform 2 was to build the module against platform 2.0 to confirm support for API changes. If API changes are necessary then, support must supposedly be added in a backwards compatible way.
In this particular case all I am trying to indicate is the module builds against platform 2.0 by submitting the changes in the pom, which means no further change is necessary, or additional backwards compatibility changes otherwise.
Frankly it is not clear to me with my limited understanding how we can be sure a module will run on platform 2.0 if it does not build against platform 2.0 with all the API changes over the versions. With more experience I might be able to see that.
Are we saying (to Wyclif's point) that to confirm module support for platform 2.0, we have to run the module on platform 2.0? Surely that would require extensive testing.

**Comment by wluyima** [comment]
You could add a maven profile where you override the openmrs version to 2.0-SNAPSHOT and make sure the build still passes

**Comment by jdegraft** [comment]
Got it, I will update my changes.

**Comment by kristopherschmidt** [comment]
To be clear, though, building against platform 2.0 is not enough, nor should it even be necessary. IMO the task should be to take the module, built against 1.7.4 / Java 6, drop it into platform 2.0 and test out all of the functionality. Plenty of issues could be hidden just by performing a build -- modules may use reflection, or JSPs, or core APIs may have changed to have dependencies on Java 8 that will only be exposed when running the 'naturally' compiled module. Isn't this how the module will be run in real life, compiled against 1.7.4? I don't believe anyone would ever run it compiled against platform 2.0 until 1.7 support is removed, so the only point of doing so seems to be to find some of the basic compile errors, before moving on to more extensive testing. Right?

**Comment by jdegraft** [comment]
Updated the pom to use profiles.
Factored version dependent changes into modules.
Added conditional module loading to load correct modules based on OpenMRS version

**Pull request closed without merging**
